dovus_filmleri = {"Kung Fu Panda" : "Panda Po, kung fu hayranıdır. Ancak ailesine ait makarna restoranında çalışır ve bu spora pek yatkın sayılmaz. Hiç beklemediği bir anda eski bir kehanetin gereğini yerine getirmek için görevlendirilince Po'nun hayalleri gerçeğe dönüşür.",
                  "Fight Club" : "Başkarakterin insomnia hastalığı ile olan mücadelesini ele alır. Doktorunun görüşüne göre insomniadan muzdarip değil ve rahatlığı çeşitli destek gruplarında hasta bir kişiymiş gibi katılarak buluyor. Sonradan, Tyler Durden adında bir adamla tanışıyor ve psikoterapi amaçlı dövüş kulübünü başlatıyor.",
                  "The Karate Kid" : "12 yaşındaki Dre Parker, babasını küçük yaşta kaybetmiştir. Annesi ve Parker, annesinin işleri nedeniyle yaşadığı Detroit'ten Çin'in başkenti Pekin'e taşınmak zorunda kalır. Kültür farklılığının ve dil bilmenin zorluluğunu yaşayan Parker, ortama uyum sağlamaya çalışır."}

romantik_filmler = {"Inception" : "Dom Cobb çok yetenekli bir hırsızdır. Uzmanlık alanı, zihnin en savunmasız olduğu rüya görme anında, bilinçaltının derinliklerindeki değerli sırları çekip çıkarmak ve onları çalmaktır. Cobb’un bu ender mahareti, onu kurumsal casusluğun tehlikeli yeni dünyasında aranan bir oyuncu yapmıştır. Ancak, aynı zamanda bu durum onu uluslararası bir kaçak yapmış ve sevdiği her şeyi kaybetmesine sebep olmuştur.",
                 "The Prestige" : "Bu beklenmedik dönüşlerle dolu gizemli öyküde, Viktorya Devri’nde iki sahne sihirbazı, giderek şiddetlenen bir savaşa ve birbirlerinin mesleki sırlarını ortaya çıkartmak için doymaz bir susuzluğa dönüşen güçlü bir rekabete girişiyorlar. Bu iki görkemli adamın cüreti tutkuya, şovmenliği bilime ve hırsı dostluğa kırdırmalarının sonuçları tehlikeli, ölümcül ve hileli oluyor. Her şey yüzyılın başında, hızla değişen Londra’da başlıyor.",
                 "V For Vendetta" : "V olarak bilinen maskeli bir adam, geleceğin totaliter rejimle yönetilen İngilteresi'nde korkuyla sindirilmiş halkına egemenliği geri verebilmek için şiddete başvuran biridir. V İngiltere halkını, kendisiyle Guy Fawkes günü olan 5 Kasım’da Parlamento’nun çevresinde buluşmaya davet eder."}

korku_filmleri = {"Devil's Advocate" : "Haklı ya da haksız gözetmeksizin kazandığı davalarla dikkat çeken Kevın Lomax (Keanu Reeves) kendisine gelen büyük teklifi reddedemez ve Florida'dan New York'a taşınır. Yeni şirketinin patronu ise, John Milton (Al Pacino) adında çok zengin ve hırslı bir adamdır.",
                  "The Others" : "İkinci dünya savaşı sonrası New Jersey... kocasını savaşta kaybetmiş olan Grace, güneş ışığına hassasiyeti olan iki çocuğuyla birlikte, büyük bir konakta yaşamaktadır. Perdelerin hep sımsıkı kapalı tutulduğu eve, üç kişi uğrar: ihtiyar bir kadın ve adam, bir de dilsiz genç kız. Evi çekip çevirecek yardımcılar aramakta olan grace, bu kişilere iş verir; onları çocuklarının sağlık durumu konusunda uyarır.",
                  "Black Swan" : "Nina (Portman), New York’ta yaşayan çok yetenekli bir balerindir ve hayatında çoğu balerin için de olduğu gibi dansetmekten başka bir şey yoktur. Eski bir balerin olan ve bu konuda çok hırslı olan annesi Erica (Hershey) ile yaşamaktadır. Oyun yönetmeni Thomas Leroy (Cassel) KUĞU GÖLÜ’nün baş balerini Beth MacIntyre (Ryder) yeni sezonda değiştrimeye karar verir ve ilk tercihi de Nina’dır."}
